system:
  delta_s: 1  # Adjust this to the length of the route
  delta_s_max: 50  # meters
  delta_s_min_interval_distance: 50000  # 50km
  delta_s_max_interval_distance: 1000000  # 1000km
  distance_between_nodes: 50 # meters
  slope_threshold: 12 # maximum degrees
  slope_variance_difference: 0.5
  batching_window_size: 20
  polyline_precision: 6
  smoothing_factor_alpha: 0.3
  default_passenger_additional_mass: 70
  api_key: "K4CH0P0-Eco-Traffic-App-Testing"
  vehicle_default_rf: 0.015
  vehicle_default_cx: 0.30
  vehicle_default_b: 0
  vehicle_default_gasoline_conversion: 9.2
  vehicle_default_diesel_conversion: 10.96
  database:
    sqlalchemy_database_uri: ${DATABASE_URI}
    sqlalchemy_track_modifications: false

plugins:
  road_information:
    - name: nominatim
      class: Nominatim
      config:
        endpoint: "http://localhost:8082/reverse?"
        road_attributes:
          - "maxspeed"

    - name: opentopodata
      class: OpenTopoData
      config:
        endpoint: "http://localhost:5000/v1/srtm30mspain?locations="

  vehicle_information:
    - name: vehicle_information_repository
      class: VehicleInformationRepository

  vehicle_engine_model:
    - name: greta_engine_model
      class: GretaEngineModel

  road_routing_services:
    - name: osrm
      class: OSRM
      config:
        endpoint: "http://localhost:5002/route/v1/driving/"
        params:
          alternatives: 3
          geometries: "geojson"
          annotations: "nodes"
          overview: "full"

    - name: graphhopper
      class: GraphHopper
      config:
        endpoint: "https://graphhopper.com/api/1/route"
        params:
          profile: "car"
          point: ''
          locale: "en"
          elevation: false
          optimize: false
          instructions: true
          calc_points: true
          debug: false
          points_encoded: false
          ch.disable: true
          heading: 0
          heading_penalty: 120
          pass_through: false
          round_trip.distance: 10000
          round_trip.seed: 0
          key: ${GRAPHHOPPER_KEY}

    - name: ors
      class: OpenRouteService
      config:
        config:
          endpoint: "http://localhost:8081/ors"
          params:
            share_factor: 0.6
            target_count: 3
            weight_factor: 0.8