DEFAULT_USER_ROUTE_ADDITIONAL_MASS = 70
DEFAULT_VEHICLE_RF = 0.015
DEFAULT_VEHICLE_CX = 0.30

DEFAULT_VEHICLE_B = 0

GRAVITY = 9.81  # Gravity

DEFAULT_GASOLINE_CONVERSION = 9.2
DEFAULT_DIESEL_CONVERSION = 10.96

