system:
  delta_s: 1  # Adjust this to the length of the route
  delta_s_max: 50  # meters
  delta_s_min_interval_distance: 50000  # 50km
  delta_s_max_interval_distance: 1000000  # 1000km
  polyline_precision: 6
  default_passenger_additional_mass: 70
  api_key: "K4CH0P0-Eco-Traffic-App-Testing"
  vehicle_default_rf: 0.015
  vehicle_default_cx: 0.30
  vehicle_default_b: 0
  vehicle_default_gasoline_conversion: 9.2
  vehicle_default_diesel_conversion: 10.96
  database:
    sqlalchemy_database_uri: ${DATABASE_URI}
    sqlalchemy_track_modifications: false
  output_variables:
    - distance # m
    - time # s
    - fuelEnergyKwh
    - fuelLiters
    - fuelLitersPer100Km
    - fuelEnergyKwhPer100Km
    - batteryEnergyKwh
    - batteryKwhPer100Km
    - model
plugins:
  road_infrastructure_provider:
    - name: nominatim
      class: Nominatim
      config:
        endpoint: "http://localhost:8082/reverse?"
        road_attributes:
          - "maxspeed"

    - name: opentopodata
      class: OpenTopoData
      config:
        endpoint: "http://localhost:5000/v1/srtm30mspain?locations="
        road_attributes:
          - "heights"

  speed_profile_provider:
    name: speed_profile
    class: SpeedProfile

  route_segmentation_provider:
    name: route_segmentator
    class: RouteSegmentator
    config:
      batching_window_size: 20
      smoothing_factor_alpha: 0.3
      slope_threshold: 12 # maximum degrees
      slope_variance_difference: 0.5
      distance_between_nodes: 50 # meters


  vehicle_information_provider:
    - name: vehicle_information_repository
      class: VehicleInformationRepository

  vehicle_energy_model_provider:
    - name: greta
      class: GretaEnergyModel
    - name: fastsim
      class: FastSimEnergyModel

  ambient_weather_provider:
    - name: openweatherapi
      class: OpenWeatherAPI
      config:
        endpoint: "https://api.openweathermap.org/data/2.5/weather"
        weather_ambient_attributes:
          - "temp"

  road_route_provider:
    - name: osrm
      class: OSRM
      config:
        endpoint: "http://localhost:5002/route/v1/driving/"
        params:
          alternatives: 1
          geometries: "geojson"
          annotations: "nodes"
          overview: "full"